training.yml adding mlflow server and run kill process for mlflow server

diff --git a/.github/workflows/training.yml b/.github/workflows/training.yml
--- a/.github/workflows/training.yml
+++ b/.github/workflows/training.yml
@@ -26,6 +26,14 @@ jobs:
     - name: Install Dependencies
       run: |
         pip3 install -U pip && pip3 install -r requirements.txt
+    
+    - name: Start MLflow Server (background)
+      run: mlflow server --host 0.0.0.0 --port 5000
+
 
     - name: Executing training pipeline
       run: python pipelines/training.py --environment=pypi run
+
+    - name: Await MLflow Server Shutdown
+      if: always()  # Run even if previous steps fail
+      run: pkill -f "mlflow server" || true # Stop the server gracefully
